clinic/urls.py
from django.urls import path
from .views import (
    home_view,
    info_view,
    department_detail_view,
    news_view,
    news_detail_view,
    doc_list_view,
    doc_detail_view,
)

app_name = 'clinic'

urlpatterns = [
    path('', home_view, name='home'),
    path('info/<int:pk>/', info_view, name='info'),
    path('department/<int:pk>/', department_detail_view, name='department'),
    path('news/', news_view, name='news'),
    path('news/<int:pk>/', news_detail_view, name='news_detail'),
    path('docs/<int:pk>/', doc_list_view, name='doc'),
    path('docs/detail/<int:pk>/', doc_detail_view, name='doc_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clinic.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinic/models.py
from django.db import models
# from ckeditor_uploader.fields import RichTextUploadingField
from .validators import validate_image_size
from django.conf import settings
from urllib.parse import urljoin


class Department(models.Model):
    picture = models.CharField(max_length=255, blank=True, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.title[:50]


class NewsCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class News(models.Model):
    keywords = models.CharField(max_length=256)
    description = models.CharField(max_length=150)
    title = models.CharField(max_length=256)
    content = models.TextField()
    image = models.CharField(max_length=255, blank=True, null=True)
    images = models.TextField(blank=True, null=True)
    created = models.DateTimeField()
    category = models.ForeignKey(NewsCategory, on_delete=models.CASCADE)
    alias = models.CharField(max_length=256, unique=True)
    published = models.BooleanField(default=False)
    viewers = models.PositiveIntegerField(default=1294)

    def __str__(self):
        return self.title[:50]


class Info(models.Model):
    keywords = models.CharField(max_length=256)
    description = models.CharField(max_length=150)
    title = models.CharField(max_length=256)
    content = models.TextField()
    alias = models.CharField(max_length=256, unique=True)

    def __str__(self):
        return self.title[:50]


class DocCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Doc(models.Model):
    title = models.CharField(max_length=256)
    doc = models.FileField(upload_to='docs/', blank=True, null=True)
    content = models.TextField()
    category = models.ForeignKey(DocCategory, on_delete=models.CASCADE)
    created = models.DateTimeField()

    def __str__(self):
        return self.title[:50]
    

class Image(models.Model):
    image = models.ImageField(upload_to='images/', validators=[validate_image_size])

    def __str__(self):
        return self.image.url
    

clinic/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Department, News, NewsCategory, Info, Doc, DocCategory

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'
        widgets = {
            'content': CKEditorWidget(),
        }


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = '__all__'
        widgets = {
            'content': CKEditorWidget(),
        }


class NewsCategoryForm(forms.ModelForm):
    class Meta:
        model = NewsCategory
        fields = '__all__'
        widgets = {
            'content': CKEditorWidget(),
        }


class InfoForm(forms.ModelForm):
    class Meta:
        model = Info
        fields = '__all__'
        widgets = {
            'content': CKEditorWidget(),
        }


class DocForm(forms.ModelForm):
    class Meta:
        model = Doc
        fields = '__all__'
        widgets = {
            'content': CKEditorWidget(),
        }


class DocCategoryForm(forms.ModelForm):
    class Meta:
        model = DocCategory
        fields = '__all__'
        widgets = {
            'content': CKEditorWidget(),
        }

clinic/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Department, News, NewsCategory, Info, Doc, DocCategory


def home_view(request):
    departments = Department.objects.all()
    latest_news = News.objects.order_by('-created').all()[:4]

    return render(request, 'home/index.html', {'departments': departments, 'latest_news': latest_news})

def info_view(request, pk):
    news_item = get_object_or_404(Info, id=pk)
    return render(request, 'info/info.html', {'info': news_item})


def news_view(request):
    category_id = request.GET.get('category_id')
    news_list = News.objects.order_by('-created').all()
    
    if category_id:
        try:
            category = NewsCategory.objects.get(id=category_id)
            news_list = news_list.filter(category=category)
        except NewsCategory.DoesNotExist:
            pass

    paginator = Paginator(news_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    news_categories = NewsCategory.objects.all()
    return render(request, 'news/news.html', {'page_obj': page_obj, 'news_categories': news_categories})

def news_detail_view(request, pk):
    news_item = get_object_or_404(News, id=pk)
    ctx = {}
    if news_item.images:
        images = news_item.images.split()
        ctx['images'] = images
    latest_news = News.objects.order_by('-created').all()[:5]
    ctx.update({'news_item': news_item, 'latest_news': latest_news})
    return render(request, 'news/news_detail.html', ctx)

def department_detail_view(request, pk):
    department = get_object_or_404(Department, id=pk)
    return render(request, 'department/department.html', {'department': department})

def doc_list_view(request, pk):
    docs_list = []
    try:
        category = DocCategory.objects.get(id=pk)
        docs_list = Doc.objects.filter(category=category)
    except NewsCategory.DoesNotExist:
        pass
    print(docs_list)
    return render(request, 'docs/docs.html', {'docs': docs_list, 'category': category})

def doc_detail_view(request, pk):
    document = get_object_or_404(Doc, id=pk)
    return render(request, 'docs/doc.html', {'doc': document})

templates/department/department.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<!-- Breadcrumbs -->
	<div class="breadcrumbs overlay">
		<div class="container">
			<div class="bread-inner">
				<div class="row">
					<div class="col-12">
						<h2>{{ department.title }}</h2>
						<ul class="bread-list">
							<li><a href="{% url "clinic:home" %}">Bosh sahifa</a></li>
							<li><i class="icofont-simple-right"></i></li>
							<li class="active">{{ department.title }}</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->

	<!-- Start Portfolio Details Area -->
	<section class="pf-details section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="inner-content">
						<div class="image-slider">
							<div class="pf-details-slider">
								<img src="{{ department.icon.url }}" alt="#">
								<img src="../img/call-bg.jpg" alt="#">
								<img src="../img/call-bg.jpg" alt="#">
							</div>
						</div>
						<div class="body-text">
							<h3>Bo'lim haqida m'lumot</h3>
							{{ department.content|safe }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Portfolio Details Area -->
{% endblock content %}

templates/docs/doc.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="bread-inner">
                <div class="row">
                    <div class="col-12">
                        <h2>{{ doc.category.name }}</h2>
                        <ul class="bread-list">
                            <li><a href="{% url "clinic:home" %}">Bosh sahifa</a></li>
                            <li><i class="icofont-simple-right"></i></li>
                            <li class="active">{{ doc.title }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Start Portfolio Details Area -->
	<section class="pf-details section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="inner-content">
						<div class="body-text">
							<h6>{{ doc.title }}</h6>
							{{ doc.content|safe }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Portfolio Details Area -->
{% endblock %}

templates/docs/docs.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="bread-inner">
                <div class="row">
                    <div class="col-12">
                        <h2>{{ category.name }}</h2>
                        <ul class="bread-list">
                            <li><a href="{% url "clinic:home" %}">Bosh sahifa</a></li>
                            <li><i class="icofont-simple-right"></i></li>
                            <li class="active">{{ category.name }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Start Portfolio Details Area -->
	<section class="pf-details section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2>Hujjatlar Ro'yxati</h2>
					{% for document in docs %}
						<div class="row">
							<div class="col-lg-10 col-md-8 col-md-12 yangilik-content-title">
								<h6>{{ forloop.counter }}. <a href="{% url "clinic:doc_detail" document.id %}" >{{ document.title }}</a></h6>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</section>
	<!-- End Portfolio Details Area -->
{% endblock %}

templates/info/info.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<!-- Breadcrumbs -->
	<div class="breadcrumbs overlay">
		<div class="container">
			<div class="bread-inner">
				<div class="row">
					<div class="col-12">
						<h2>{{ info.title }}</h2>
						<ul class="bread-list">
							<li><a href="{% url "clinic:home" %}">Bosh sahifa</a></li>
							<li><i class="icofont-simple-right"></i></li>
							<li class="active">{{ info.title }}</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->

	<!-- Start Portfolio Details Area -->
	<section class="pf-details section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="inner-content">
						<div class="image-slider">
							<div class="pf-details-slider">
								<img src="{% static "img/call-bg.jpg" %}" alt="#">
								<img src="{% static "img/call-bg.jpg" %}" alt="#">
								<img src="{% static "img/call-bg.jpg" %}" alt="#">
							</div>
						</div>
						<div class="body-text">
							{{ info.content|safe }}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Portfolio Details Area -->
{% endblock %}

templates/news/news.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
    <!-- Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="bread-inner">
                <div class="row">
                    <div class="col-12">
                        <h2>{% blocktrans %}Yangiliklar{% endblocktrans %}</h2>
                        <ul class="bread-list">
                            <li><a href="../index.html">{% blocktrans %}Bosh sahifa{% endblocktrans %}</a></li>
                            <li><i class="icofont-simple-right"></i></li>
                            <li class="active">{% blocktrans %}Yangiliklar{% endblocktrans %}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <section class="yangilik-content news-single">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-8 col-md-12 main-sidebar-link1">
                    <h2>{% blocktrans %}So'ngi yangiliklar{% endblocktrans %}</h2>
                    <div class="d-flex align-items-start ">
                        <div class="tab-content" id="v-pills-tabContent">
                            <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel"
                                aria-labelledby="v-pills-home-tab" tabindex="0">
                                {% if page_obj %}
                                    {% for item in page_obj %}
                                        <div class="row">
                                            <div class="col-lg-10 col-md-8 col-md-12 yangilik-content-title">
                                                <h3><a href="{% url "clinic:news_detail" item.id %}" >{{ item.title }}</a></h3>
                                                <span>{{ item.description }}</span>
                                                <div class="row">
                                                    <div class="  meta-yangilik-category">
                                                        <div class="m-left">
                                                            <span class="date"><i class="fa fa-calendar" aria-hidden="true"></i>
                                                                {{ item.created }}</span>
                                                        </div>
                                                        <div class="m-right">
                                                            <span class="views"><i class="fa fa-eye"></i>{% blocktrans %}Ko'rishlar soni{% endblocktrans %} {{ item.viewers }}</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-2 col-md-4 col-md-12">
                                                <img src="{{ host }}{{ item.image }}" alt="">
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <div class="row">
                                        <div class="col-lg-10 col-md-8 col-md-12 yangilik-content-title">
                                            <h3><a href="#" >{% blocktrans %}Yangiliklar mavjud emas{% endblocktrans %}</a></h3>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                            <!-- Pagination -->
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if category_id %}&category_id={{ category_id }}{% endif %}" aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                    {% for num in page_obj.paginator.page_range %}
                                        {% if page_obj.number == num %}
                                            <li class="page-item active"><a class="page-link">{{ num }}</a></li>
                                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                            <li class="page-item"><a class="page-link" href="?page={{ num }}{% if category_id %}&category_id={{ category_id }}{% endif %}">{{ num }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if category_id %}&category_id={{ category_id }}{% endif %}" aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-4 col-md-12 main-sidebar-link">
                    <h2>{% blocktrans %}Mavzular{% endblocktrans %}</h2>
                    <div id="v-pills-tab" role="tablist" aria-orientation="vertical ">
                        {% for category in news_categories %}
                            <div class=" nav-link active" id="v-pills-home-tab" data-bs-toggle="pill"
                                data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home"
                                aria-selected="true">
                                <a class=" nav-link active" href="{% url "clinic:news" %}?category_id={{ category.id }}">{{ category.name }}</a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/news/news_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
	<!-- Breadcrumbs -->
	<div class="breadcrumbs overlay">
		<div class="container">
			<div class="bread-inner">
				<div class="row">
					<div class="col-12">
						<h2>{% blocktrans %}Yangiliklar{% endblocktrans %}</h2>
						<ul class="bread-list">
							<li><a href="{% url "clinic:home" %}">{% blocktrans %}Bosh sahifa{% endblocktrans %}</a></li>
							<li><i class="icofont-simple-right"></i></li>
							<li><a href="{% url "clinic:news_detail" news_item.id %}">{% blocktrans %}Yangiliklar{% endblocktrans %}</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumbs -->

	<!-- Start Portfolio Details Area -->
	<section class="pf-details section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="inner-content">
						<div class="image-slider">
							<div class="pf-details-slider">
								<img src="{{ host }}{{ news_item.image }}" alt="#">
								{% for image in images %}
									<img src="{{ host }}{{ image }}" alt="#">
								{% endfor %}
							</div>
						</div>
						<div class="body-text">
							<h3>{{ news_item.title }}</h3>
							<div class="meta d-flex justify-content-between align-items-center py-2">
								<div class="meta-left">
									<span class="date text-muted">
										<i class="fa fa-calendar"></i> {{ news_item.created }}
									</span>
								</div>
								<div class="meta-right">
									<span class="views text-muted">
										<i class="fa fa-eye"></i> {% blocktrans %}Ko'rishlar soni{% endblocktrans %} {{ news_item.viewers }}
									</span>
								</div>
							</div>
							<p style="text-align: justify; text-indent: 20px;">{{ news_item.content|safe }}</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Portfolio Details Area -->

{% endblock %}